In [1]:
import numpy as np

Create our student **DATASET:**





In [2]:
students = np.array([
    [85, 78, 92],
    [65, 72, 68],
    [95, 91, 89],
    [45, 52, 48],
    [76, 81, 79]
])

print(students)

[[85 78 92]
 [65 72 68]
 [95 91 89]
 [45 52 48]
 [76 81 79]]


**Think of this as a table:**
Students with subject names called Python,Statistics,DataVisualization and thier Marks


**UNDERSTAND THE ARRAY:**

In [3]:
print(students.shape)

(5, 3)


**THIS MEANS:**
5 rows
3 columns

In [4]:
print(students.ndim)

2


That's because our data is a **2-dimensional array**.

In [5]:
print(students.size)

15


5 × 3 = 15;5-Rows,3-Coloumns


**Access individual data:**

Let's access Student 1's Python mark:

In [6]:
print(students[0, 0])

85


EXAMPLES:

In [7]:
print(students[2, 1])


print(students[4, 2])

91
79


**Calculate total marks:**

Now we start doing actual analysis.


We want each student's total.

In [8]:
total_marks = np.sum(students, axis=1)

print(total_marks)

[255 205 275 145 236]


**Important concept:** axis=1

Student 1 → 85 + 78 + 92

Student 2 → 65 + 72 + 68

...

**Calculate average marks:**

In [9]:
average_marks = np.mean(students, axis=1)

print(average_marks)

[85.         68.33333333 91.66666667 48.33333333 78.66666667]


In [10]:
average_marks = np.round(np.mean(students, axis=1), 2)

print(average_marks)

[85.   68.33 91.67 48.33 78.67]


**Find the highest-performing student:**

In [11]:
highest_index = np.argmax(average_marks)

print(highest_index)

2


Let's make the output more understandable:

In [12]:
print("Highest performing student: Student", highest_index + 1)
print("Average:", average_marks[highest_index])

Highest performing student: Student 3
Average: 91.67


**Find the lowest-performing student:**

In [13]:
lowest_index = np.argmin(average_marks)

print("Lowest performing student: Student", lowest_index + 1)
print("Average:", average_marks[lowest_index])

Lowest performing student: Student 4
Average: 48.33


This uses:

np.argmax() → largest value

np.argmin() → smallest value

**Find students who failed:**

In [14]:
failed = students < 50

print(failed)

[[False False False]
 [False False False]
 [False False False]
 [ True False  True]
 [False False False]]


True means condition satisfies.

False means condition not satisfies.

Now we can find students who have **at least one failed subject:**

In [15]:
failed_students = np.any(students < 50, axis=1)

print(failed_students)

[False False False  True False]


**Subject-wise analysisS:**

Python Marks:

In [16]:
python_marks = students[:, 0]

print("Python Marks:", python_marks)

Python Marks: [85 65 95 45 76]


Statistics marks:

In [18]:
statistics_marks = students[:, 1]

print("Statistics Marks:", statistics_marks)

Statistics Marks: [78 72 91 52 81]


Data Visualization marks:

In [19]:
data_visualization_marks = students[:, 2]

print("Data Visualization Marks:", data_visualization_marks)

Data Visualization Marks: [92 68 89 48 79]


**Calculate subject averages:**

In [20]:
python_avg = np.mean(python_marks)
statistics_avg = np.mean(statistics_marks)
data_visualization_avg = np.mean(data_visualization_marks)

print("Python Average:", python_avg)
print("Statistics Average:", statistics_avg)
print("Data Visualization Average:", data_visualization_avg)

Python Average: 73.2
Statistics Average: 74.8
Data Visualization Average: 75.2


Instead of calculating each column separately, NumPy can calculate all subject averages at once:

In [21]:
subject_averages = np.mean(students, axis=0)

print(subject_averages)

[73.2 74.8 75.2]


**Find the highest mark in each subject:**

In [22]:
highest_subject_marks = np.max(students, axis=0)

print(highest_subject_marks)

[95 91 92]


This tells us:

Python              → 95

Statistics          → 91

Data Visualization  → 92

**Calculate standard deviation:**

In [23]:
std_marks = np.std(students, axis=0)

print(std_marks)

[17.23252738 12.95221989 15.99249824]


**Simple interpretation**


If standard deviation is:

Small

↓

Marks are relatively close together

Large

↓





Marks are more spread out

---



---



**Create student rankings 🏆:**

In [25]:
ranking = np.argsort(average_marks)[::-1]

print("STUDENT RANKING")
print("----------------")

for rank, index in enumerate(ranking, start=1):
    print(
        "Rank", rank,
        "- Student", index + 1,
        "- Average:", average_marks[index]
    )

STUDENT RANKING
----------------
Rank 1 - Student 3 - Average: 91.67
Rank 2 - Student 1 - Average: 85.0
Rank 3 - Student 5 - Average: 78.67
Rank 4 - Student 2 - Average: 68.33
Rank 5 - Student 4 - Average: 48.33




---



---



---



**--END--**

